import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Strategic Planning for Effective Customer Service</a><br />
          and<br />
          <a>Analyzing Web Traffic</a><br />
          are<br />
          the two courses<br />that I <a className={styles.red}>love</a> the most.
        </h1>
      </main>
    </div>
  )
}
